version: "3"
services:
  strapi:
    container_name: versalles-node
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}

      DATABASE_PORT: 3306
      DATABASE_HOST: versalles-db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    volumes:
      - ./src:/node-app/src
      - ./public/uploads:/node-app/public/uploads
    ports:
      - "${PORT}:${PORT}"
    networks:
      - versalles-network
    depends_on:
      - strapiDB

  strapiDB:
    container_name: versalles-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - versalles-volume:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - versalles-network

volumes:
  versalles-volume:

networks:
  versalles-network:
    name: versalles-network
    driver: bridge
